### ISSUE TITLE
画面設計

### ISSUE THREAD

**Issue by omorirenka** [morijyobi/python_flask_web_final_exercise_2023-omorirenka#1]
## ToDo
- [x] 利用者ログイン画面の作成
- [x] 利用者新規登録画面の作成
- [x] 利用者パスワードリセット画面の作成
- [x] メイン画面の作成
- [x] 収支金額登録画面の作成
- [x] 年の収支確認画面の作成
- [x] 月の収支確認画面の作成
- [x] カテゴリ検索結果画面の作成
- [x] 固定費確認・変更画面の作成
- [x] カテゴリ追加画面の作成
- [x] 管理者ログイン画面の作成
- [x] 管理者画面の作成

**Comment by omorirenka** [comment]
## 利用者ログイン画面のデザイン案
![利用者ログイン画面](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/0b393193-1d98-489e-9da7-df5ddbf38db5)

**Comment by omorirenka** [comment]
## 利用者新規登録画面のデザイン案
![利用者新規登録画面](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/01ec2bbc-cf27-40d0-a55a-a4c789481c68)

**Comment by omorirenka** [comment]
## 利用者パスワードリセット画面のデザイン案
![利用者パスワードリセット画面](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/9154b152-b13a-468f-9e4c-bc0b3938a10c)

**Comment by omorirenka** [comment]
## メイン画面のデザイン案
![ホーム](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/bc6e6265-d2c1-4600-9d54-0a72c0ac59d5)

**Comment by omorirenka** [comment]
## 収支金額登録画面のデザイン案
![収支金額登録](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/642275b9-0776-4fd8-afd8-bc5960ccf341)

**Comment by omorirenka** [comment]
## 年の収支確認画面のデザイン案
![年の収支](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/a1b2a9f0-f3a7-4015-9e90-b38c43b9058a)

**Comment by omorirenka** [comment]
## 月の収支確認画面のデザイン案
![月の収支](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/7b4420b5-9b85-417b-bbc1-db7895c9ddbf)

**Comment by omorirenka** [comment]
## カテゴリ検索結果画面のデザイン案
![カテゴリ検索結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/e1168fc5-4ea2-435d-b766-5b1f95ccc5e2)

**Comment by omorirenka** [comment]
## 固定費確認・変更画面のデザイン案
![固定費確認・変更](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/0fba9dce-e6b7-4375-85c3-9d2ca38d2987)

**Comment by omorirenka** [comment]
## カテゴリ追加画面のデザイン案
![カテゴリ追加](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/89aab3e8-d73e-4641-b227-124758923d44)

**Comment by omorirenka** [comment]
## 管理者ログイン画面のデザイン案
![管理者ログイン画面](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/0e886cb6-10d9-4db2-9750-4d8ffd483218)

**Comment by omorirenka** [comment]
## 管理者画面のデザイン案
![管理者画面](https://github.com/morijyobi/python_flask_web_final_exercise_2023-omorirenka/assets/113155231/aa246640-f17e-4069-ac48-9c958633e4eb)

**Comment by hosokawa3217** [comment]
「作成中」のラベルが付いています。　

### ラベルを削除するか「完了」ラベルに変更しましょう！
